resources:
  - ../base/todo-frontend
  - ../base/todo-backend
  - ../base/postgres
  - namespace.yaml

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: todo-frontend
    spec:
      replicas: 1   # prod = HA setup
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: todo-backend
    spec:
      replicas: 1
