apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: postgres
  namespace: prod
spec:
  releaseName: postgres
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: "12.x.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      username: todo_user
      password: todo_pass
      database: todo_db
    primary:
      persistence:
        enabled: false
