apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 12.12.10
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      username: todo_user
      password: todo_pass
      database: todo_db
    primary:
      persistence:
        enabled: true
        size: 1Gi
