apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: postgres
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 12.5.7
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    global:
      postgresql:
        auth:
          username: todo_user
          password: todo_pass
          database: todo_db
    primary:
      persistence:
        enabled: true
        size: 1Gi
