apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/vikashyogendrarao/todo-frontend:v1
        env:
          - name: REACT_APP_API_URL
            value: "http://todo-backend:3000"
        ports:
        - containerPort: 80
