apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: todo-prod
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: prod
