resources:
  - ../base/todo-frontend
  - ../base/todo-backend
  - ../base/postgres

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: todo-frontend
    spec:
      replicas: 1   # smaller for QA
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: todo-backend
    spec:
      replicas: 1
