apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - ../qa-kustomization.yaml
  - ../uat-kustomization.yaml
  - ../stg-kustomization.yaml
  - ../prod-kustomization.yaml
  - ../bitnami-repo.yaml
